---
functional:
  - Пользователь имеет возможность зарегистрироваться 
  - Пользователь имеет возможность создать игру без регистрации
  - Пользователь имеет возможность авторизоваться
  - Пользователь имеет возможность создать игру с ботом
  - Пользователь имеет возможность создать игру с другом    
  - Пользователь имеет возможность создать игру с другим пользователем
  - Пользователь побеждает, когда написал верный код
  - Пользователь проигрывает, когда вводит неверный код
  - Пользователь имеет возможность сдаться. когда нажимает на кнопку GIVE UP
  - Пользователь имеет возможность выбрать уровень сложности игры
  - Пользователь имеет возможность создать турнир
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть кроссбраузерным
  - Сайт должен быть способен обрабатывать большое количество трафика

implicit:
  - Платформа должна обеспечить возможность игры двух юзеров
