---
functional:
  - Пользователь имеет возможность зарегистрироваться 
  - Пользователь имеет возможность создать игру без регистрации
  - Пользователь имеет возможность авторизоваться
  - Пользователь имеет возможность создать игру с ботом
  - Пользователь имеет возможность создать игру с другом     ПОЛЬЗ2 АВТОРИЗ ДАННЫЕ ВИДИТ ПРИГЛАС ССОГЛАШ НАЧАЛАСЬ ИГРА
  - Пользователь имеет возможность создать игру с другим пользователем
  - Пользователь побеждает, когда написал верный код
  - Пользователь проигрывает, когда вводит не верный код
  - Пользователь имеет возможность сдаться. когда нажимает на кнопку
  - Пользователь имеет возможность выбирать время игры
  - Пользователь имеет возможность выбрать уровень сложности игры
  - Пользователь имеет возможность выбрать задание
  - Пользователь имеет возможность выбрать задание опираясь на теги
  
non-functional:
  - Адаптивность
  - Локализация
  -
  - Сайт выдерживает 1000 пользователей онлайн
implicit:
  -
  - Платформа должна обеспечить возможность игы двух юзеров
