---
functional:
  - Пользователь имеет возможность создать игру с ботом
  - Пользователь имеет возможность создать игру с другом
  - Пользователь имеет возможность создать игру с неизвестным противником
non-functional:
  - 
  - Сайт выдерживает 1000 пользователей онлайн
implicit:
  -
  - Платформа должна обеспечить возможность игы двух юзеров
